const TopReplies = [
  'Top!',
  '@nome, topzera?',
  '@nome, eu to voando alto, mlk!',
  '@nome, fiquei sabendo de uma parada bem TOOOOOOOOOOOOOOOOP!',
  'mas você @nome, é top das galaxias!!',
  '@nome é cria mermo. Top Demais!',
  'Aí o @nome topzou demais. Pega o Oakley que a topzisse brilhou, brother!',
  // Grafia incorreta propositalmente
  '@nome tá top assim porque conserteza saiu comigo.',
  '@nome é muito top. Seu carro é automático?',
  '@nome, sua topzisse bateu no meu Copo Stanley e encheu ele de cerveja.',
  '@nome Tudo bem ser top assim. Tenho até amigos que são...',
  'Pra falar essas coisas @nome, eu já sei que é amigo do @ManukiTaTop.',
  'Não tem nada mais Lek Topzera do que viajar pra São Paulo de férias todo mês',
  'Todo Lek Topster que eu conheço tem um Fox, sabia?',
  'Tá top, tá top, tá é muita onda, essa live tá bombando e eu sou muito top!',
  // mahtfTop é um emote de inscrito do canal de MahTF, inscrição acabou.
  // 'Você já disse a @ManukiTanuki que é topster hoje? mahtfTop',
  'Você sabia que a Lady Gaga fez uma música pro filme TOP Gun: Maverick?',
  'Somente pessoas tops chegaram até aqui',
  'E aí? Vamo numa baladinha top?',
  'Você me deixou sem palavras, então vou mandar um ª pra você',
  'Sabe o que seria top agora? Uma coquinha gelada.',
  'Eu sou um bot Topster, caso queira me remover do seu canal, ou adicionar-lo em seu canal, fale com @mahtf por sussurro',
  'Passou mal porque não consome Top Therm. Por @GuiFernandes1607',
  'Meus jogos preferidos são sTOP e TOP Gear. Por @GuiFernandes1607',
  'Por quê ela tem cabelo grande? Porque TOP é TUDO! Por @GuiFernandes1607',
  'Maior bruxo da história é o Harry Topper. Por @GuiFernandes1607',
  'Minha série favorita é HearthsTOPper. Por @Loester_10control',
  'Seu topete não sai da minha cabeça',
  'Sempre que eu penso no meu TOP 3, você está la!',
  'Você sabe quais são os Pokémon\'s Favoritos de Manukita? . . . KabuTOPs e HitmonTOP. Por @Gata_Amaldicoada',
  'Nada é mais top que você!',
  'Caso você tenha tenha uma frase bem topster, mande por sussurro para @mahtf',
  '@MahTF está cada dia adicionando novas frases, mas não é um trabalho fácil.',
  'Muito top né?',
  '@nome, eu achei que isso foi top também, acredita?',
  'topssímo de mais!',
  'Beba água e seja top você também!',
  'Você pode ser top, mas tão top, mas tão top, que... esqueci o que ia dizer, mas era algo bem top',
  'Se alguém tenta destopizar você, essa pessoa não te merece, seja top!',
  'Qual foi a coisa mais top de hoje? Você, é claro!',
  'Eu tinha dois tatus, o Tatudo e o Tatop, o Tatudo morreu, quem ficou? Por @lukezitto_',
  'Você é mais top que uma estátua grega feita em mármore.',
  'Qual é o romance que manukita topster mais ama? HeartsTOPper. por @f00xes',
  'Já tomou seu lactopurga recentemente?',
  'Ei. . .  tu é top né? Por @Gata_amaldicoada',
  'Dica THOP: Você sabia que é top visitar seu dentista a cada 06 meses?',
  'Quem é a pessoa mais top? Para o cego, é a luz :sunny: Para o faminto, é o pão :bread: Para o sedento, é a fonte de água :droplet: Para o morto, é a vida :herb: Para o enfermo, é a cura :syringe: Para o prisioneiro, é a liberdade :butterfly: Para o solitário, é o companheiro :two_men_holding_hands: Para o viajante, é o caminho :person_running: Para mim, é você!',
  'Oi pessoa belíssima na minha tela, tudo topster?',
  'Quando foi sua últíma consulta com um ortopedista?',
  'Chat, você sabia que @nome é topster? Não? Agora tá sabendo!',
  'Me diz uma frase bem top agora, por favor!',
  ':top:',
  'Aí você foi muito mais que top, você foi topíssimo!',
  'E ai @nome, tudo topster?',
  'Eu cansei de conversa fiada, agora eu quero é um papo top com você @nome!',
  'Festa top tem que ter camarote, gata... Se não tem ala vip eu nem entro! Por: @ricky_cezar',
  'VillaMix ontem foi top de mais, cê tinha que ver',
  'O sofrimento do streamer é topster para o chat e o enche de entreterimento!',
  'Você é top de mais!',
  'Só mais um episódio da sua topzeirisse, por favor!',
  'Me falaram que aqui é o ambiente mais top de todos!',
  'Lavar as mãos é top de mais!',
  'Ei, bora ali? Eu super topo!',
  'Eu ouvi dizer que você topa muitas coisas, bora topar mais uma?',
  'Hoje a gente tá só com assuntos top de mais, não é mesmo?',
  'Voa lek, maior satisfação te encontrar aqui. Sextou?',
  'Subtember chegou e sabe o que é mais top? #HypeTrain',
  'Subs são tops de mais!',
  'To tão titi, cadê um Hype train bem top?',
  'I think I lost my top hat!',
  'Qual é a coisa mais top que você fez hoje?',
  'Esse jogo é top de mais, né?',
  'Estou com vontade de jogar um Top Gear, topa?',
];

export { TopReplies };
