const TopReplies = [
  'Top!',
  '@nome, topzera?',
  '@nome, eu to voando alto, mlk!',
  '@nome, fiquei sabendo de uma parada bem TOOOOOOOOOOOOOOOOP!',
  'mas você @nome, é top das galaxias!!',
  '@nome é cria mermo. Top Demais!',
  'Aí o @nome topzou demais. Pega o Oakley que a topzisse brilhou, brother!',
  // Grafia incorreta propositalmente
  '@nome tá top assim porque conserteza saiu comigo.',
  '@nome é muito top. Seu carro é automático?',
  '@nome, sua topzisse bateu no meu Copo Stanley e encheu ele de cerveja.',
  '@nome Tudo bem ser top assim. Tenho até amigos que são...',
  'Pra falar essas coisas @nome, eu já sei que é amigo do @ManukiTaTop.',
  'Não tem nada mais Lek Topzera do que viajar pra São Paulo de férias todo mês',
  'Todo Lek Topster que eu conheço tem um Fox, sabia?',
  'Tá top, tá top, tá é muita onda, essa live tá bombando e eu sou muito top!',
  // mahtfTop é um emote de inscrito do canal de MahTF
  'Você já disse a @ManukiTanuki que é topster hoje? mahtfTop',
  'Você sabia que a Lady Gaga fez uma música pro filme TOP Gun: Maverick?',
  'Somente pessoas tops chegaram até aqui',
  'E aí? Vamo numa baladinha top?',
  'Você me deixou sem palavras, então vou mandar um ª pra você',
  'Sabe o que seria top agora? Uma coquinha gelada.',
  'Eu sou um bot Topster, caso queira me remover do seu canal, ou adicionar-lo em seu canal, fale com @mahtf',
  'Passou mal porque não consome Top Therm. Por @GuiFernandes1607',
  'Meus jogos preferidos são sTOP e TOP Gear. Por @GuiFernandes1607',
  'Por quê ela tem cabelo grande? Porque TOP é TUDO! Por @GuiFernandes1607',
  'Maior bruxo da história é o Harry Topper. Por @GuiFernandes1607',
  'Minha série favorita é HearthstTOPer. Por @Loester_10control',
  'Seu topete não sai da minha cabeça',
  'Sempre que eu penso no meu TOP 3, você está la!',
  'Você sabe quais são os Pokémon\'s Favoritos de Manukita? . . . KabuTOPs e HitmonTOP. Por @Gata_Amaldicoada',
  'Nada é mais top que você!',
]

export { TopReplies };
